# Generated by Django 4.0.6 on 2022-08-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='visibilidad',
            field=models.CharField(choices=[('P', 'Publico'), ('X', 'Privado')], default='X', max_length=1),
        ),
    ]
