# Generated by Django 4.0.6 on 2022-08-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_equipos'),
        ),
    ]
